version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"  # Ollama API exposed on host
    volumes:
      - /ollama_data:/root/.ollama
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"  # WebUI exposed on host
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434  # Access Ollama from WebUI
    volumes:
      - /openwebui_data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
