version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /ollama_data:/root/.ollama
    networks:
      ollama_net:
        ipv4_address: 172.16.100.10
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    volumes:
      - /openwebui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      ollama_net:
        ipv4_address: 172.16.100.11
    restart: unless-stopped

networks:
  ollama_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24
